/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'itdbd' at '14/12/01 10:29' with Gradle 2.2.1
 *
 * @author itdbd, @date 14/12/01 10:29
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
